version: "0.5"
ordered_shutdown: true

log_configuration:
  disable_json: true
  add_timestamp: true
  timestamp_format: "06-01-02 15:04:05.000"
  no_color: true
  flush_each_line: true

processes:
  postgres:
    disabled: false
    command: docker compose up postgres
    ready_log_line: "database system is ready to accept connections"
    log_location: ./logs/postgres.log
    shutdown:
      command: docker compose down postgres -t 30

  web:
    disabled: false
    command: |
      uv sync --locked &&
      uv run alembic upgrade head &&
      uv run flask --app "watcher:create_app()" run --host=127.0.0.1 --port=8000
    ready_log_line: "Running on http://127.0.0.1"
    log_location: ./logs/web.log
    availability:
      exit_on_end: true
    depends_on:
      postgres:
        condition: process_log_ready
    shutdown:
      signal: 15
      timeout_seconds: 5

  worker:
    disabled: true
    command: uv run python -m watcher.worker
    log_location: ./logs/worker.log
    availability:
      restart: "no"
      exit_on_end: false
    depends_on:
      postgres:
        condition: process_log_ready
