# Generated by Django 6.0.7 on 2026-07-10 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failure", "Failure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_summary", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=2000)),
                (
                    "selector_type",
                    models.CharField(
                        choices=[("css", "CSS"), ("xpath", "XPath")], default="css", max_length=10
                    ),
                ),
                ("selector", models.TextField()),
                (
                    "processor_type",
                    models.CharField(
                        choices=[("raw_text", "Raw text"), ("min_value", "Minimum value")],
                        default="raw_text",
                        max_length=50,
                    ),
                ),
                ("processor_config", models.JSONField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        blank=True,
                        choices=[("success", "Success"), ("failure", "Failure")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("last_raw_text", models.TextField(blank=True, null=True)),
                ("last_processed_text", models.TextField(blank=True, null=True)),
                ("last_error_message", models.TextField(blank=True, null=True)),
                ("last_duration_ms", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_at", models.DateTimeField(auto_now_add=True)),
                ("raw_text", models.TextField(blank=True, null=True)),
                ("processed_text", models.TextField(blank=True, null=True)),
                ("changed", models.BooleanField(default=False)),
                ("previous_processed_text", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="watch.run",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="watch.target",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
