# Generated by Django 6.0.7 on 2026-07-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="fetch_method",
            field=models.CharField(
                choices=[("httpx", "HTTPX"), ("brightdata", "Bright Data")],
                default="httpx",
                max_length=50,
            ),
        ),
    ]
